umbrella_admin_notification_:
  resource: "@UmbrellaAdminBundle/Controller/NotificationController.php"
  type: annotation

umbrella_admin_job_:
  resource: "@UmbrellaAdminBundle/Controller/JobController.php"
  type: annotation

umbrella_admin_filewriter_:
  resource: "@UmbrellaAdminBundle/Controller/FileWriterController.php"
  type: annotation

umbrella_user:
  resource: "@UmbrellaAdminBundle/Resources/config/user_routing.yml"